//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAGE_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalizeDoctori
    {
        public int AnaizeId { get; set; }
        public Nullable<int> PacientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> Hemoleucograma { get; set; }
        public Nullable<int> Eritrocite { get; set; }
        public Nullable<int> Leucocite { get; set; }
        public Nullable<int> Glicemie { get; set; }
        public Nullable<int> Electroliti { get; set; }
        public Nullable<int> Colesterol { get; set; }
        public Nullable<int> Hemoglobina { get; set; }
        public Nullable<int> EcografieAbdominala { get; set; }
        public Nullable<int> RadiografiePulmonara { get; set; }
        public Nullable<int> EKG { get; set; }
        public Nullable<int> Magneziemia { get; set; }
        public Nullable<int> Creatinina { get; set; }
        public Nullable<int> Uree { get; set; }
        public Nullable<int> Ecocardiografie { get; set; }
        public Nullable<int> PRP { get; set; }
        public Nullable<int> ExamenlampaWood { get; set; }
        public Nullable<int> SumaTotala { get; set; }
    
        public virtual Doctori Doctori { get; set; }
        public virtual Pacienti Pacienti { get; set; }
    }
}
