//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAGE_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalizePacienti
    {
        public int AnalizeId { get; set; }
        public Nullable<int> PacientId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Hemoleucograma { get; set; }
        public string Eritrocite { get; set; }
        public string Leucocite { get; set; }
        public string Glicemie { get; set; }
        public string Electroliti { get; set; }
        public string Colesterol { get; set; }
        public string Hemoglobina { get; set; }
        public string EcografieAbdominala { get; set; }
        public string RadiografiePulmonara { get; set; }
        public string EKG { get; set; }
        public string Magneziemia { get; set; }
        public string Creatinina { get; set; }
        public string Uree { get; set; }
        public Nullable<int> SumaTotala { get; set; }
        public string Ecocardiografie { get; set; }
        public string PRP { get; set; }
        public string Infiltratie { get; set; }
        public string ExamenlampaWood { get; set; }
        public Nullable<int> Completate { get; set; }
    }
}
