//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAGE_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistenti
    {
        public int AsistentId { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string NrTel { get; set; }
        public string Email { get; set; }
        public Nullable<int> Gen { get; set; }
        public string CNP { get; set; }
        public Nullable<System.DateTime> DataNastere { get; set; }
        public string Specializare { get; set; }
        public Nullable<int> Salariu { get; set; }
        public Nullable<int> SalonId { get; set; }
    
        public virtual Saloane Saloane { get; set; }
    }
}
