//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAGE_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctori()
        {
            this.AnalizeDoctoris = new HashSet<AnalizeDoctori>();
            this.Programari_Pacienti = new HashSet<Programari_Pacienti>();
        }
    
        public int DoctorId { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string NrTel { get; set; }
        public string Email { get; set; }
        public Nullable<int> Gen { get; set; }
        public string CNP { get; set; }
        public Nullable<System.DateTime> DataNastere { get; set; }
        public string Specializare { get; set; }
        public Nullable<int> CodParafa { get; set; }
        public string Parola { get; set; }
        public string Interval_lucru { get; set; }
        public string DespreMine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalizeDoctori> AnalizeDoctoris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programari_Pacienti> Programari_Pacienti { get; set; }
    }
}
