//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAGE_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturi_Pacienti
    {
        public int FisaId { get; set; }
        public Nullable<int> NrZileSpitalizare { get; set; }
        public Nullable<int> CostSpitalizare { get; set; }
        public Nullable<int> PacientId { get; set; }
    
        public virtual Pacienti Pacienti { get; set; }
    }
}
