//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAGE_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programari_Pacienti
    {
        public int ProgramareId { get; set; }
        public Nullable<System.DateTime> Ziua { get; set; }
        public string Ora { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> PacientId { get; set; }
        public string Specializarea { get; set; }
        public Nullable<int> Internare { get; set; }
        public Nullable<int> Stare { get; set; }
        public string NumePacient { get; set; }
        public string PrenumePacient { get; set; }
        public string EmailPacient { get; set; }
        public string NrTelPacient { get; set; }
        public string NumarSalon { get; set; }
    
        public virtual Doctori Doctori { get; set; }
        public virtual Pacienti Pacienti { get; set; }
    }
}
